### ISSUE TITLE
Unable to subscribe to SNS topic using ImportValue

### ISSUE THREAD

**Issue by nason** [totallymoney/serverless-sns-to-sqs-events#3]
I'm trying to create a new queue, subscribing to an existing SNS topic but am getting an error:

```
  TypeError: Cannot read property 'replace' of undefined
      at ServerlessSnsToSqsEvents.getLogicalId (/app/node_modules/@totallymoney/serverless-sns-to-sqs-events/src/index.js:33:44)
      at ServerlessSnsToSqsEvents.getOrCreateSnsTopic (/app/node_modules/@totallymoney/serverless-sns-to-sqs-events/src/index.js:127:29)
```

Using config something like:

```yaml
events:
      - snsToSqs:
          sns:
              Fn::ImportValue: MyEventNotificationTopic
          sqs:
              queueName: ${self:provider.stage}-${self:service}-queue
```

It looks like its expecting `sns.displayName` to be set as well, but I'm unclear how to give an existing topic and a display name: https://github.com/totallymoney/serverless-sns-to-sqs-events/blob/master/src/index.js#L127

Could it be that the `isArn` function is looking for a `Fn::Import` key instead of a `Fn::ImportValue` key? https://github.com/totallymoney/serverless-sns-to-sqs-events/blob/master/src/index.js#L29

I'd be happy to open a PR to fix this, let me know what you think. Thanks!
